<%@ page contentType="text/html;charset=UTF-8"%>
<%@ include file="/WEB-INF/jsp/manage/common/taglibs.jsp"%>
<div style="padding: 5px;font-family:微软雅黑;">
<table class="tableForm" width="100%">
	<tr>
		<th>ID:</th>
		<td>${actionLog.id}</td>
	</tr>					
	<tr>
		<th width="25%">行为Key:</th>
		<td>${actionLog.actionKey}</td>
	</tr>					
	<tr>
		<th>行为名称:</th>
		<td>${actionLog.actionName}</td>
	</tr>
	<tr>
		<th>行为分组:</th>
		<td>${actionLog.actionGroup}</td>
	</tr>
	<tr>
		<th>URL:</th>
		<td>${actionLog.actionUrl}</td>
	</tr>					
	<tr>
		<th>用户:</th>
		<td>${actionLog.userKey}</td>
	</tr>
	<tr>
		<th>cookies:</th>
		<td>${actionLog.cookies}</td>
	</tr>
	<tr>
		<th>访问时间:</th>
		<td><fmt:formatDate value="${actionLog.actionTime}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
	</tr>
	<tr>
		<th>访问数据:</th>
		<td>${actionLog.data}</td>
	</tr>
	<tr>
		<th>平台:</th>
		<td>${actionLog.os.message}</td>
	</tr>
	<tr>
		<th>渠道:</th>
		<td>${actionLog.channel.message}</td>
	</tr>					
	<tr>
		<th>渠道信息:</th>
		<td>${actionLog.channelInfo}</td>
	</tr>					
	<tr>
		<th>渠道版本:</th>
		<td>${actionLog.channelVersion}</td>
	</tr>					
	<tr>
		<th>访问IP:</th>
		<td>${actionLog.userIp}</td>
	</tr>					
	<tr>
		<th>运营商:</th>
		<td>${actionLog.isp}</td>
	</tr>					
	<tr>
		<th>国家:</th>
		<td>${actionLog.country}</td>
	</tr>					
	<tr>
		<th>省:</th>
		<td>${actionLog.region}</td>
	</tr>					
	<tr>
		<th>市:</th>
		<td>${actionLog.city}</td>
	</tr>					
	<tr>
		<th>经纬度:</th>
		<td>${actionLog.lntLat}</td>
	</tr>

</table>
</div>
